sudo: required
dist: trusty
before_install: make -f travis/Makefile prepare_environment
os:
  - linux
  - osx
language: cpp
compiler:
  - clang
script:
  - make -f travis/Makefile run-tests
  - make -f travis/Makefile pre-deploy
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - build/src/kcov_osx_x64
    - build/src/kcov_linux_x64
  on:
    tags: true
notifications:
  recipients:
    - ander.ender@gmail.com
  email:
    on_success: change
    on_failure: always
