sudo: required
dist: trusty
before_install: make -f travis/Makefile prepare_environment
os:
  - linux
  - osx
language: cpp
compiler:
  - clang

stages:
  script:
  - make -f travis/Makefile run-tests
  - cp build/src/kcov build/src/kcov-bin_${TRAVIS_OS_NAME}_x64
  - grep linux $TRAVIS_OS_NAME && pip install exodus-bundler && exodus build/src/kcov && mv exodus-kcov-bundle.sh kcov-bundle_linux_x64
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  file:
    - build/src/kcov-bin_osx_x64
    - kcov-bundle_linux_x64
  on:
    tags: true
notifications:
  recipients:
    - ander.ender@gmail.com
  email:
    on_success: change
    on_failure: always
